game_resolution:
- 3440
- 1440
scene_templates:
  cat_stats_screen:
    file: templates/cat_stats_header.png
    match_threshold: 0.8
    match_region:
    - 0
    - 0
    - 400
    - 100
regions:
  cat_name:
    rect:
    - 588
    - 53
    - 208
    - 78
    allowlist: ''
    preprocess:
    - grayscale
    - threshold
  cat_age:
    rect:
    - 559
    - 140
    - 129
    - 43
    allowlist: ''
    preprocess:
    - grayscale
    - threshold
  cat_level:
    rect:
    - 506
    - 201
    - 127
    - 50
    allowlist: ''
    preprocess:
    - grayscale
    - threshold
  stat_str:
    allowlist: 0123456789-+
    preprocess:
    - grayscale
    - threshold
    - resize2x
    icon_file: images/characteristics/Stat_Strength.png
    rect_total:
    - 590
    - 268
    - 57
    - 50
    rect_base:
    - 655
    - 271
    - 42
    - 47
    rect_bonus:
    - 701
    - 270
    - 38
    - 45
  stat_dex:
    allowlist: 0123456789-+
    preprocess:
    - grayscale
    - threshold
    - resize2x
    icon_file: images/characteristics/Stat_Dexterity.png
    rect_total:
    - 592
    - 326
    - 54
    - 49
    rect_base:
    - 652
    - 329
    - 44
    - 45
    rect_bonus:
    - 701
    - 328
    - 39
    - 45
  stat_con:
    allowlist: 0123456789-+
    preprocess:
    - grayscale
    - threshold
    - resize2x
    icon_file: images/characteristics/Stat_Constitution.png
    rect_total:
    - 589
    - 379
    - 59
    - 55
    rect_base:
    - 652
    - 384
    - 45
    - 50
    rect_bonus:
    - 699
    - 387
    - 41
    - 43
  stat_int:
    allowlist: 0123456789-+
    preprocess:
    - grayscale
    - threshold
    - resize2x
    icon_file: images/characteristics/Stat_Intelligence.png
    rect_total:
    - 816
    - 210
    - 52
    - 55
    rect_base:
    - 876
    - 211
    - 42
    - 50
    rect_bonus:
    - 926
    - 215
    - 37
    - 44
  stat_spd:
    allowlist: 0123456789-+
    preprocess:
    - grayscale
    - threshold
    - resize2x
    icon_file: images/characteristics/Stat_Speed.png
    rect_total:
    - 818
    - 267
    - 49
    - 46
    rect_base:
    - 876
    - 269
    - 48
    - 46
    rect_bonus:
    - 927
    - 268
    - 40
    - 44
  stat_cha:
    allowlist: 0123456789-+
    preprocess:
    - grayscale
    - threshold
    - resize2x
    icon_file: images/characteristics/Stat_Charisma.png
    rect_total:
    - 815
    - 321
    - 52
    - 53
    rect_base:
    - 877
    - 323
    - 44
    - 47
    rect_bonus:
    - 926
    - 324
    - 40
    - 45
  stat_lck:
    allowlist: 0123456789-+
    preprocess:
    - grayscale
    - threshold
    - resize2x
    icon_file: images/characteristics/Stat_Luck.png
    rect_total:
    - 815
    - 380
    - 54
    - 52
    rect_base:
    - 875
    - 381
    - 46
    - 47
    rect_bonus:
    - 922
    - 380
    - 45
    - 46
