"""Look up item effect text from the Mewgenics wiki Items table.

Files ``item_effects_wiki.json``, ``item_icons_wiki.json``, and
``item_slots_wiki.json`` are generated by ``tools/generate_item_effects_wiki.py``
from https://mewgenics.wiki.gg/wiki/Items (PascalCase keys derived from display
names).  Icons are wiki ``ITEM_*.svg`` URLs; **Slot** is the wiki table column
(Weapon, Head, Face, Neck, Trinket, Consumable, …).  Save files use the same
PascalCase internal ids for most items; ``ITEM_ID_ALIASES`` covers known
mismatches.
"""

from __future__ import annotations

import json
import logging
from functools import lru_cache
from pathlib import Path
from typing import Any, cast

log = logging.getLogger("mewgent.data.item_effects")

# Save-file id -> wiki Items table key (same keys as item_effects_wiki.json).
# Wiki display names often differ slightly from game ids; a few rows are absent on the wiki.
ITEM_ID_ALIASES: dict[str, str] = {
    # Save id is shared; wiki splits armor vs trinket rows — trinket is pure -99 Luck.
    "BrokenMirror": "BrokenMirror_Trinket",
    # Typo in save / wiki spelling.
    "Dumbell": "Dumbbell",
    # Display name "Empty Water Bottle" -> EmptyWaterBottle.
    "WaterBottle_Empty": "EmptyWaterBottle",
    # Apostrophe: "Survivalist's Gaiter" -> Survivalist'sGaiter.
    "SurvivalistGaiter": "Survivalist'sGaiter",
    # No "Catnip Big" row; closest large consumable is "Large Catnip Baggy".
    "CatnipBig": "LargeCatnipBaggy",
    # No "Dry Bone Hat" row; wiki has Helm / Mask / Necklace for the same set.
    "DryBoneHat": "DryBoneHelm",
}


@lru_cache(maxsize=1)
def _wiki_effects() -> dict[str, str]:
    path = Path(__file__).resolve().parent / "item_effects_wiki.json"
    if not path.is_file():
        log.warning("Missing item effects data: %s", path)
        return {}
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        log.warning("Could not load item effects JSON: %s", e)
        return {}
    return cast(dict[str, str], raw)


@lru_cache(maxsize=1)
def _wiki_icons() -> dict[str, str]:
    path = Path(__file__).resolve().parent / "item_icons_wiki.json"
    if not path.is_file():
        return {}
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        log.warning("Could not load item icons JSON: %s", e)
        return {}
    return cast(dict[str, str], raw)


@lru_cache(maxsize=1)
def _wiki_slots() -> dict[str, str]:
    path = Path(__file__).resolve().parent / "item_slots_wiki.json"
    if not path.is_file():
        return {}
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        log.warning("Could not load item slots JSON: %s", e)
        return {}
    return cast(dict[str, str], raw)


def item_effect_for_id(item_id: str) -> str | None:
    """Return wiki description for an internal item id, or None if unknown."""
    if not item_id:
        return None
    key = ITEM_ID_ALIASES.get(item_id, item_id)
    return _wiki_effects().get(key)


def item_icon_url_for_id(item_id: str) -> str | None:
    """Return wiki CDN URL for the item's table icon, or None if unknown."""
    if not item_id:
        return None
    key = ITEM_ID_ALIASES.get(item_id, item_id)
    return _wiki_icons().get(key)


def item_slot_for_id(item_id: str) -> str | None:
    """Return wiki **Slot** column (e.g. Weapon, Head, Trinket), or None if unknown."""
    if not item_id:
        return None
    key = ITEM_ID_ALIASES.get(item_id, item_id)
    return _wiki_slots().get(key)


def item_effect_entry(item_id: str) -> dict[str, Any]:
    """Payload fragment for WebChannel JSON."""
    return {
        "item_id": item_id,
        "effect": item_effect_for_id(item_id),
        "icon_url": item_icon_url_for_id(item_id),
        "slot": item_slot_for_id(item_id),
    }
